apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:fae138f701522c617f5be6b7746e391115a6fb6935f94e82d2dc871f1d22f0fe
  name: quay.io/rh-ee-srehman/dotnetcore
  newName: quay.io/rh-ee-srehman/dotnetcore
