apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:ab058de6012e9f6e9ba5fd593f245dc490796a5ea52cfcec89b1fd1b03b87cc8
  name: quay.io/rh-ee-srehman/dotnetcore
  newName: quay.io/rh-ee-srehman/dotnetcore
