apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:abd51518e45b0ef7be055148d496808aad9089f8cd126bea1c5f6da52e07be51
  name: quay.io/rh-ee-srehman/dotnetcore
  newName: quay.io/rh-ee-srehman/dotnetcore
